
version: '2.1'

volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    network_mode: host
    container_name: prometheus_data_aws
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    
    expose:
      - 9090
   
  grafana:
    image: grafana/grafana:9.5.2
    network_mode: host
    container_name: grafana_data_aws
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  
    expose:
      - 3000
    
 
